name = "SOCRATES"
uuid = "254d33cd-9ba8-4636-9aa1-7555a57e289d"
authors = ["Stuart Daines <stuart.daines@gmail.com>"]
version = "13.0.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
libSOCRATES_C_jll = "5efd3cc6-0bfe-56c5-886d-e8fa04bb9153"

[compat]
libSOCRATES_C_jll = "13.0"

[extras]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["NCDatasets", "Plots", "Test"]
